# Generated by Django 6.0.2 on 2026-02-10 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной шаблон', max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный шаблон')),
                ('subject', models.CharField(default='Kommercheskoe predlozhenie (KP)', max_length=200, verbose_name='Тема письма')),
                ('body_text', models.TextField(blank=True, default='', help_text='Можно оставить пустым — тогда будет отправляться только HTML.', verbose_name='Текст письма (TEXT)')),
                ('body_html', models.TextField(blank=True, default='', help_text='Переменные: {{vacancy}}, {{city}}, {{company}}, {{manager}}, {{email}}, {{phone}}, {{ad_url}}, {{source}}', verbose_name='Текст письма (HTML)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон КП',
                'verbose_name_plural': 'Шаблоны КП',
            },
        ),
        migrations.CreateModel(
            name='SalesLeadImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='sales_imports/', verbose_name='Excel-файл лидов')),
            ],
            options={
                'verbose_name': 'Импорт лидов',
                'verbose_name_plural': 'Импорт лидов',
            },
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Компания')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='Источник')),
                ('ad_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на объявление')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('email', models.CharField(blank=True, default='', max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('vacancy', models.CharField(blank=True, default='', max_length=200, verbose_name='Вакансия')),
                ('work_types', models.TextField(blank=True, default='', verbose_name='Тип работ')),
                ('staff_count', models.IntegerField(blank=True, null=True, verbose_name='Кол-во персонала')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('kp_sent', 'КП отправлено'), ('reply', 'Ответ получен'), ('negotiation', 'Переговоры'), ('agreement', 'Согласование условий'), ('contract', 'Договор / запуск'), ('rejected', 'Отказ / не актуально')], default='new', max_length=40, verbose_name='Статус')),
                ('kp_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки КП')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Лид продаж',
                'verbose_name_plural': 'Лиды продаж',
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Тема')),
                ('text', models.TextField(blank=True, default='', verbose_name='Заметка')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время (когда сделать)')),
                ('remind_at', models.DateTimeField(blank=True, null=True, verbose_name='Уведомить в')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='Уведомление отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.saleslead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'Заметка/задача по лиду',
                'verbose_name_plural': 'Заметки/задачи по лидам',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SalesRoundRobinState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_robin_last_manager', to=settings.AUTH_USER_MODEL, verbose_name='Последний назначенный менеджер')),
            ],
            options={
                'verbose_name': 'Round-robin состояние',
                'verbose_name_plural': 'Round-robin состояние',
            },
        ),
    ]
