# Generated by Django 6.0.2 on 2026-02-10 08:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('hall_worker', 'Работник торгового зала'), ('cleaner', 'Уборщица')], max_length=50, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file_left', models.FileField(upload_to='reconciliation/', verbose_name='Сверка от Заказчика')),
                ('file_right', models.FileField(upload_to='reconciliation/', verbose_name='Выгрузка с базы')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reconciliation/reports/', verbose_name='Отчёт (Excel)')),
                ('status', models.CharField(choices=[('uploaded', 'Загружено'), ('processing', 'В обработке'), ('done', 'Готово'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('result', models.TextField(blank=True, default='', verbose_name='Результат сверки')),
            ],
            options={
                'verbose_name': 'Сверка',
                'verbose_name_plural': 'Сверка',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('source_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Почта отправителя')),
                ('source_type', models.CharField(choices=[('merch', 'Выкладка'), ('cleaning', 'Клининг')], default='merch', max_length=30, verbose_name='Тип заявки')),
                ('file_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Хэш файла')),
                ('excel_file', models.FileField(upload_to='requests/', verbose_name='Excel-файл заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterModelOptions(
            name='saleslead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лид продаж', 'verbose_name_plural': 'Лиды продаж'},
        ),
        migrations.AlterModelOptions(
            name='salesroundrobinstate',
            options={'verbose_name': 'Распределение (состояние)', 'verbose_name_plural': 'Распределение (состояние)'},
        ),
        migrations.AddField(
            model_name='kptemplate',
            name='kp_docx',
            field=models.FileField(blank=True, help_text='Если загрузишь .docx — CRM может прикреплять его как вложение (опционально).', null=True, upload_to='kp_templates/', verbose_name='КП (Word .docx)'),
        ),
        migrations.AddField(
            model_name='kptemplate',
            name='short_text',
            field=models.TextField(blank=True, default='', help_text='Короткое сообщение в теле письма (если нужно).', verbose_name='Короткий текст письма (в тело)'),
        ),
        migrations.AddField(
            model_name='salesroundrobinstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='ad_url',
            field=models.CharField(blank=True, default='', max_length=700, verbose_name='Ссылка на объявление'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Например: HH.ru, Avito, VK, 2ГИС, Сайт, Рекомендация', max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='staff_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во персонала'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('kp_sent', 'КП отправлено'), ('reply', 'Ответ получен'), ('negotiation', 'Переговоры'), ('agreement', 'Согласование условий'), ('deal', 'Договор / запуск'), ('rejected', 'Отказ / не актуально')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='vacancy',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='work_types',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Тип работ'),
        ),
        migrations.AlterField(
            model_name='salesleadimport',
            name='excel_file',
            field=models.FileField(default='exit', upload_to='sales_imports/', verbose_name='Excel/CSV файл лидов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesroundrobinstate',
            name='last_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_robin_last_manager', to=settings.AUTH_USER_MODEL, verbose_name='Последний менеджер'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('full_name_norm', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ФИО (нормализ.)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('card_number', models.CharField(max_length=30, verbose_name='Номер карты')),
                ('account_number', models.CharField(max_length=30, verbose_name='Номер счета')),
                ('bik', models.CharField(max_length=15, verbose_name='БИК')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Банк')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('positions', models.ManyToManyField(blank=True, to='app.position', verbose_name='Должности')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес (без города)')),
                ('address_raw', models.TextField(verbose_name='Адрес объекта (как в Excel)')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=10, verbose_name='Статус')),
                ('current_hours_merch', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Часы (текущие) выкладка')),
                ('current_hours_cleaning', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Часы (текущие) клининг')),
                ('assigned_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='app.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'unique_together': {('city', 'address')},
            },
        ),
        migrations.CreateModel(
            name='RequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255, verbose_name='Вид оказываемых услуг')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Часы')),
                ('row_hash', models.CharField(max_length=64, verbose_name='Хэш строки')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee', verbose_name='Назначенный сотрудник')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.request', verbose_name='Заявка')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Строка заявки',
                'verbose_name_plural': 'Строки заявки',
                'unique_together': {('request', 'row_hash')},
            },
        ),
        migrations.CreateModel(
            name='StoreShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('service_type', models.CharField(choices=[('cleaning', 'Клининг'), ('merch', 'Выкладка')], max_length=30, verbose_name='Услуга')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Часы')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee', verbose_name='Сотрудник')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='app.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'indexes': [models.Index(fields=['date', 'service_type'], name='app_storesh_date_48bb7e_idx'), models.Index(fields=['employee', 'date'], name='app_storesh_employe_37de34_idx')],
                'unique_together': {('store', 'date', 'service_type')},
            },
        ),
    ]
