# Generated by Django 6.0.2 on 2026-02-10 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_leadnote_options_alter_leadnote_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadnote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.saleslead', verbose_name='Лид'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напомнить'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание отправлено'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст заметки'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок'),
        ),
    ]
